[package]
name = "porkbun-dns-buddy"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0"
home = "0.5.9"
chrono = "0.4.38"
